name: Manual workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  downloadAndRunSG:
    name: download-and-run-sg
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      - name: Download-and-run-SG
        run: |
          curl -o sg.zip https://packages.couchbase.com/releases/couchbase-sync-gateway/3.0.0-beta02/couchbase-sync-gateway-community_3.0.0-beta02_x86_64.zip
          tar -zxvf sg.zip
          ./couchbase-sync-gateway/bin/sync_gateway vendor/couchbase-lite-core/Replicator/tests/data/config.json & sleep 10
      - name: Select-Device
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'`
          echo $device | cat >device
          echo "Selected the device : ${device}"
      - name: "Build-for-testing"
        run: |
          export CBL_TEST_HOST=localhost
          DEVICE=$(cat device)
          xcodebuild build-for-testing -scheme "CBL_ObjC" -project CouchbaseLite.xcodeproj  -destination "platform=iOS Simulator,name=${DEVICE}"
      - name: "Test"
        run: |
          DEVICE=$(cat device)
          xcodebuild test-without-building -scheme "CBL_ObjC" -project CouchbaseLite.xcodeproj  -destination "platform=iOS Simulator,name=${DEVICE}"
